sonar.projectKey=996a43847d3e5b38c362e8793cc4d19a5d8d06ce
sonar.organization=y
sonar.sources=backend,front-end/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.qualitygate.wait=true
