sonar.projectKey=yuujin12_BigFat-Pizza
sonar.organization=yuujin12
sonar.sources=backend,front-end/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.qualitygate.wait=true
