name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./front-end
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./front-end
        run: npm test

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./front-end
        run: npm ci

      # - name: Lint Frontend
      #   working-directory: ./front-end
      #   run: npm run lint

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      # - name: Lint Backend
      #   working-directory: ./backend
      #   run: npm run lint