name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./front-end
        run: npm ci --cache ./front-end/node_modules

      # - name: Run Frontend Tests
      #   working-directory: ./front-end
      #   run: npm test

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci --cache ./backend/node_modules

      # - name: Run Backend Tests
      #   working-directory: ./backend
      #   run: npm test