name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./front-end
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock
          fi
          npm ci

      - name: Run Frontend Tests
        working-directory: ./front-end
        run: npm test

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock
          fi
          npm ci

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test