name: Manual Deploy Pizza App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Remove cache option since we'll handle it manually
          
      - name: Install Frontend Dependencies
        working-directory: ./front-end
        run: |
          npm ci
          npm run build

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-frontend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-frontend:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-backend:latest