name: Manual Deploy Pizza App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Frontend Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./front-end/node_modules
            ~/.npm
          key: ${{ runner.os }}-frontend-${{ hashFiles('./front-end/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Cache Backend Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./backend/node_modules
            ~/.npm
          key: ${{ runner.os }}-backend-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install Frontend Dependencies
        working-directory: ./front-end
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./front-end
        run: npm test
        
      - name: Build Frontend
        working-directory: ./front-end
        run: npm run build

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pizza-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pizza-frontend:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-frontend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-frontend:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pizza-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pizza-backend:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pizza-backend:latest